services:
  - type: web
    name: guess-game-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3 