name: CI

on:
  push:
    branches:
      - main
      - feature/test-improvements
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Redis
      run: sudo apt-get update && sudo apt-get install -y redis-server
    - name: Initialize database
      run: |
        sudo service redis-server start
        PYTHONPATH=. python init_db.py

    - name: Install black
      run: pip install black

    - name: Check code formatting with black
      run: |
        black --check .

    - name: Run tests with coverage
      run: |
        pip install pytest-cov
        PYTHONPATH=. pytest --cov=bot --cov-report=term-missing -vv tests/